export type SpecialFindingSeverity = 'slight' | 'abnormal' | 'serious';

export type SpecialFindingRule = {
  code: string;
  displayName: string;
  aliases: RegExp[];
  suggestion: string;
  defaultSeverity: SpecialFindingSeverity;
  negativeAliases?: RegExp[];
};

const rule = (
  code: string,
  displayName: string,
  aliases: RegExp[],
  suggestion: string,
  defaultSeverity: SpecialFindingSeverity = 'abnormal',
  negativeAliases: RegExp[] = [],
): SpecialFindingRule => ({
  code,
  displayName,
  aliases,
  suggestion,
  defaultSeverity,
  negativeAliases,
});

export const DEFAULT_NEGATIVE_FINDING_PATTERNS: RegExp[] = [
  /未见(?:明显)?异常/,
  /未见/,
  /无(?:明显)?异常/,
  /未发现/,
  /未查见/,
  /阴性/,
  /正常/,
  /除外/,
  /排除/,
];

export const SPECIAL_FINDING_LIBRARY: SpecialFindingRule[] = [
  rule('BMI_HIGH', '体重指数(BMI)增高', [/体重指数.*(?:增高|偏高)/i, /\bBMI\b.*(?:增高|偏高|超重|肥胖)/i], '建议结合饮食、运动和腰围管理进行体重控制', 'slight'),
  rule('OVERWEIGHT', '超重', [/(?:^|[\s:：])超重(?:$|[\s,，;；])/i], '建议控制总能量摄入并规律运动，定期监测体重', 'slight'),
  rule('OBESITY', '肥胖', [/(?:^|[\s:：])肥胖(?:$|[\s,，;；])/i], '建议结合 BMI、腰围和代谢指标进行系统体重管理', 'abnormal'),
  rule('CENTRAL_OBESITY', '中心性肥胖', [/中心性肥胖/i, /腹型肥胖/i], '建议重点控制腰围并筛查代谢综合征相关风险', 'abnormal'),
  rule('WAIST_HIGH', '腰围增高', [/腰围.*(?:增高|偏高|超标)/i], '建议结合体脂和血压血脂指标评估代谢风险', 'slight'),
  rule('UNDERWEIGHT', '体重偏低', [/体重过低/i, /体重偏低/i, /消瘦/i], '建议评估营养摄入、消化吸收和体重变化情况', 'slight'),

  rule('THYROID_NODULE', '甲状腺结节', [/甲状腺.*结节/i], '建议结合甲状腺超声分级与专科意见定期复查', 'abnormal'),
  rule('THYROID_CYST', '甲状腺囊肿', [/甲状腺.*囊肿/i], '建议结合甲状腺超声表现和甲功结果随访', 'slight'),
  rule('THYROID_ECHO_UNEVEN', '甲状腺回声欠均匀', [/甲状腺.*回声(?:欠均匀|不均匀|不均|欠均)/i], '建议结合甲功和甲状腺抗体评估是否存在弥漫性病变', 'slight'),
  rule('THYROID_DIFFUSE', '甲状腺弥漫性病变', [/甲状腺弥漫性病变/i], '建议结合甲功、抗体及超声表现进一步评估', 'abnormal'),
  rule('THYROID_ENLARGED', '甲状腺肿大', [/甲状腺肿大/i, /甲状腺增大/i], '建议结合甲功与压迫症状评估甲状腺状态', 'slight'),
  rule('THYROID_CALCIFICATION', '甲状腺钙化灶', [/甲状腺.*钙化/i], '建议结合超声分级和专科意见随访', 'abnormal'),
  rule('HASHIMOTO_LIKE', '桥本样改变', [/桥本(?:甲状腺炎)?/i, /桥本样改变/i], '建议结合甲状腺抗体及甲功进一步判断', 'abnormal'),
  rule('FATTY_LIVER', '脂肪肝', [/脂肪肝(?:\((?:轻度|中度|重度)\))?/i], '建议结合体重、血脂和肝功能进行综合管理并定期复查', 'abnormal', [/脂肪肝与/i]),

  rule('BREAST_NODULE', '乳腺结节', [/乳腺.*结节/i], '建议结合乳腺超声分级和乳腺专科意见定期复查', 'abnormal'),
  rule('BREAST_CYST', '乳腺囊肿', [/乳腺.*囊肿/i], '建议结合乳腺超声表现定期随访', 'slight'),
  rule('BREAST_HYPERPLASIA', '乳腺增生', [/乳腺增生/i], '建议结合月经周期和乳腺症状定期复查', 'slight'),
  rule('BREAST_LOBULAR_HYPERPLASIA', '乳腺小叶增生', [/乳腺小叶增生/i], '建议结合乳腺超声和症状变化定期复查', 'slight'),
  rule('BREAST_FIBROADENOMA', '乳腺纤维腺瘤', [/乳腺.*纤维腺瘤/i], '建议结合乳腺超声分级与专科意见定期复查', 'abnormal'),
  rule('BREAST_DUCT_DILATION', '乳腺导管扩张', [/乳腺导管扩张/i], '建议结合乳腺专科意见和症状变化评估', 'slight'),
  rule('BREAST_CALCIFICATION', '乳腺钙化', [/乳腺.*钙化/i, /簇状钙化/i], '建议结合乳腺影像分级进一步评估', 'abnormal'),

  rule('TCT_INFLAMMATION', '宫颈TCT轻度炎症反应性改变', [/TCT.*(?:轻度炎症|炎症反应性细胞改变|良性反应性改变)/i], '建议结合妇科检查和医生意见定期复查宫颈筛查', 'slight'),
  rule('TCT_ASCUS', '宫颈TCT ASC-US', [/TCT.*ASC-US/i, /ASC-US/i], '建议结合 HPV 检测和妇科专科意见进一步评估', 'abnormal'),
  rule('TCT_ASCH', '宫颈TCT ASC-H', [/TCT.*ASC-H/i, /ASC-H/i], '建议尽快结合阴道镜等检查进一步评估', 'serious'),
  rule('TCT_LSIL', '宫颈TCT LSIL', [/TCT.*LSIL/i, /LSIL/i, /低度鳞状上皮内病变/i], '建议结合 HPV 检测和阴道镜进一步评估', 'abnormal'),
  rule('TCT_HSIL', '宫颈TCT HSIL', [/TCT.*HSIL/i, /HSIL/i, /高度鳞状上皮内病变/i], '建议尽快到妇科专科进一步评估和处理', 'serious'),
  rule('HPV_POSITIVE', 'HPV阳性', [/HPV.*阳性/i, /阳性.*HPV/i], '建议结合 TCT 结果和妇科专科意见评估宫颈风险', 'abnormal'),
  rule('UTERINE_FIBROID', '子宫肌瘤', [/子宫肌瘤/i], '建议结合肌瘤大小、位置和症状定期复查妇科超声', 'abnormal'),
  rule('ADENOMYOSIS', '子宫腺肌症', [/子宫腺肌症/i], '建议结合月经情况和妇科专科意见进一步评估', 'abnormal'),
  rule('ENDOMETRIAL_POLYP', '子宫内膜息肉', [/子宫内膜息肉/i], '建议结合妇科超声和月经情况复查', 'abnormal'),
  rule('CERVICAL_NABOTHIAN_CYST', '宫颈纳囊', [/宫颈纳囊/i, /宫颈囊肿/i], '建议结合妇科检查定期观察', 'slight'),
  rule('CERVICAL_POLYP', '宫颈息肉', [/宫颈息肉/i], '建议结合妇科专科意见评估处理时机', 'abnormal'),
  rule('CERVICAL_HYPERTROPHY', '宫颈肥大', [/宫颈肥大/i], '建议结合妇科检查和炎症情况综合评估', 'slight'),
  rule('PELVIC_EFFUSION', '盆腔积液', [/盆腔积液/i], '建议结合月经期、症状及妇科专科意见判断意义', 'slight'),
  rule('OVARIAN_CYST', '卵巢囊肿', [/卵巢囊肿/i], '建议结合囊肿大小和月经周期定期复查', 'abnormal'),
  rule('ADNEXAL_CYST', '附件囊肿', [/附件囊肿/i], '建议结合妇科超声定期复查', 'abnormal'),
  rule('ADNEXAL_MASS', '附件包块', [/附件包块/i], '建议尽快结合妇科超声和专科意见进一步评估', 'serious'),
  rule('VAGINITIS', '阴道炎', [/阴道炎/i], '建议结合白带检查和妇科专科意见规范处理', 'slight'),
  rule('CERVICITIS', '宫颈炎', [/宫颈炎/i], '建议结合妇科检查和病原学结果综合评估', 'slight'),
  rule('VULVAR_LEUKOPLAKIA', '外阴白斑', [/外阴白斑/i], '建议尽快结合妇科专科意见进一步评估和规范处理', 'abnormal'),

  rule('LUNG_NODULE', '肺结节', [/肺.*结节/i], '建议结合胸部 CT 大小、密度和随访建议定期复查', 'abnormal'),
  rule('LUNG_MICRONODULE', '肺小结节', [/肺.*小结节/i, /微小结节/i], '建议结合胸部 CT 随访建议定期复查', 'slight'),
  rule('GROUND_GLASS_NODULE', '磨玻璃结节', [/磨玻璃结节/i], '建议结合胸部 CT 随访方案定期复查', 'abnormal'),
  rule('LUNG_MARKINGS', '肺纹理增多', [/肺纹理(?:增多|增粗|紊乱)/i], '建议结合呼吸道症状和胸片/CT 表现综合判断', 'slight'),
  rule('CHRONIC_BRONCHITIS', '慢性支气管炎', [/慢性支气管炎/i], '建议戒烟并结合呼吸科意见评估肺功能', 'abnormal'),
  rule('EMPHYSEMA', '肺气肿', [/肺气肿/i], '建议结合呼吸科意见和肺功能检查进一步评估', 'abnormal'),
  rule('PLEURAL_THICKENING', '胸膜增厚', [/胸膜增厚/i], '建议结合既往炎症史和影像随访判断意义', 'slight'),
  rule('LUNG_CALCIFICATION', '肺部钙化灶', [/肺.*钙化灶/i, /肺.*钙化影/i], '建议结合既往炎症或结核史综合判断', 'slight'),
  rule('OLD_LUNG_LESION', '肺部陈旧灶', [/肺.*陈旧灶/i, /陈旧性病灶/i], '建议结合既往感染史和影像随访判断', 'slight'),
  rule('PULMONARY_BULLA', '肺大疱', [/肺大疱/i], '建议结合呼吸科意见评估破裂风险和肺功能', 'abnormal'),
  rule('BRONCHIECTASIS', '支气管扩张', [/支气管扩张/i], '建议结合咳嗽咳痰史和呼吸科意见进一步评估', 'abnormal'),
  rule('PULMONARY_FIBROSIS', '肺纤维化灶', [/肺.*纤维化/i, /纤维条索影/i], '建议结合既往炎症史和影像随访判断', 'slight'),

  rule('LIVER_CYST', '肝囊肿', [/肝囊肿/i], '建议结合囊肿大小和超声表现定期复查', 'slight'),
  rule('LIVER_HEMANGIOMA', '肝血管瘤', [/肝血管瘤/i], '建议结合影像特征和肝胆专科意见随访', 'abnormal'),
  rule('LIVER_CALCIFICATION', '肝内钙化灶', [/肝内.*钙化/i, /肝.*钙化灶/i], '建议结合既往炎症史和超声表现综合判断', 'slight'),
  rule('INTRAHEPATIC_STONE', '肝内胆管结石', [/肝内胆管结石/i], '建议结合症状和肝胆外科意见评估处理方案', 'abnormal'),
  rule('GALLBLADDER_POLYP', '胆囊息肉', [/胆囊息肉/i], '建议结合息肉大小和数量定期复查腹部超声', 'abnormal'),
  rule('GALLBLADDER_STONE', '胆囊结石', [/胆囊结石/i], '建议结合腹痛等症状和肝胆外科意见评估', 'abnormal'),
  rule('CHOLECYSTITIS', '胆囊炎', [/胆囊炎/i], '建议结合症状和肝胆专科意见进一步评估', 'abnormal'),
  rule('GALLBLADDER_WALL_ROUGH', '胆囊壁毛糙', [/胆囊壁毛糙/i, /胆囊壁增厚/i], '建议结合胆囊炎症状和复查超声判断', 'slight'),
  rule('ADENOMYOMATOSIS', '胆囊腺肌症', [/胆囊腺肌症/i], '建议结合超声表现和肝胆专科意见随访', 'abnormal'),
  rule('CBD_DILATION', '胆总管扩张', [/胆总管扩张/i], '建议结合肝胆实验室检查和影像进一步评估', 'abnormal'),
  rule('PANCREAS_ECHO_STRONG', '胰腺回声增强', [/胰腺回声增强/i], '建议结合血脂血糖和腹部影像综合判断', 'slight'),
  rule('PANCREATIC_CYST', '胰腺囊肿', [/胰腺囊肿/i], '建议结合腹部影像和专科意见进一步评估', 'abnormal'),
  rule('PANCREATIC_DILATED_DUCT', '胰管扩张', [/胰管扩张/i], '建议结合胰腺影像和专科意见进一步评估', 'abnormal'),
  rule('SPLEEN_ENLARGED', '脾肿大', [/脾肿大/i], '建议结合血常规和腹部超声进一步评估', 'abnormal'),
  rule('SPLEEN_CYST', '脾囊肿', [/脾囊肿/i], '建议结合囊肿大小和影像表现定期复查', 'slight'),
  rule('SPLEEN_CALCIFICATION', '脾钙化灶', [/脾.*钙化/i], '建议结合既往炎症史综合判断', 'slight'),

  rule('RENAL_CYST', '肾囊肿', [/肾囊肿/i], '建议结合囊肿大小和影像分型定期复查', 'slight'),
  rule('RENAL_STONE', '肾结石', [/肾结石/i], '建议多饮水并结合泌尿外科意见评估处理', 'abnormal'),
  rule('RENAL_HYDRONEPHROSIS', '肾积水', [/肾积水/i], '建议结合泌尿系梗阻原因进一步评估', 'abnormal'),
  rule('RENAL_ANGIOMYOLIPOMA', '肾错构瘤', [/肾错构瘤/i], '建议结合大小和泌尿外科意见定期复查', 'abnormal'),
  rule('RENAL_CALCIFICATION', '肾钙化灶', [/肾.*钙化灶/i], '建议结合既往炎症或结石史综合判断', 'slight'),
  rule('BLADDER_STONE', '膀胱结石', [/膀胱结石/i], '建议结合泌尿外科意见评估处理方案', 'abnormal'),
  rule('BLADDER_WALL_THICK', '膀胱壁增厚', [/膀胱壁增厚/i], '建议结合尿常规和泌尿系统症状评估', 'slight'),
  rule('BLADDER_POLYP', '膀胱息肉', [/膀胱息肉/i], '建议结合泌尿外科意见进一步评估', 'abnormal'),
  rule('PROSTATE_HYPERPLASIA', '前列腺增生', [/前列腺增生/i], '建议结合尿频夜尿情况和泌尿外科意见评估', 'abnormal'),
  rule('PROSTATE_CALCIFICATION', '前列腺钙化', [/前列腺.*钙化/i], '建议结合泌尿外科意见和症状综合判断', 'slight'),
  rule('PROSTATE_CYST', '前列腺囊肿', [/前列腺囊肿/i], '建议结合囊肿大小和专科意见定期复查', 'slight'),
  rule('PROSTATE_ENLARGED', '前列腺增大', [/前列腺增大/i], '建议结合 PSA、排尿症状和泌尿外科意见评估', 'abnormal'),
  rule('VARICOCELE', '精索静脉曲张', [/精索静脉曲张/i], '建议结合泌尿男科意见和症状程度进一步评估', 'abnormal'),

  rule('CAROTID_PLAQUE', '颈动脉斑块', [/颈动脉.*斑块/i], '建议结合血脂、血压和心血管风险进行管理', 'abnormal', [/预测因子/i]),
  rule('CAROTID_IMT', '颈动脉内膜增厚', [/颈动脉.*(?:内中膜增厚|内膜增厚|IMT增厚)/i], '建议结合血脂血压和生活方式进行干预', 'slight'),
  rule('ATHEROSCLEROSIS', '动脉粥样硬化', [/动脉粥样硬化/i], '建议结合血脂、血压和心血管专科意见综合管理', 'abnormal', [/危险因素/i, /预测因子/i, /见于[:：]?/i, /动脉硬化趋势/i]),
  rule('SINUS_BRADYCARDIA', '窦性心动过缓', [/窦性心动过缓/i], '建议结合症状和运动基础评估是否需要进一步检查', 'slight'),
  rule('SINUS_TACHYCARDIA', '窦性心动过速', [/窦性心动过速/i], '建议结合休息状态、甲功和心血管情况综合评估', 'slight'),
  rule('SINUS_ARRHYTHMIA', '窦性心律不齐', [/窦性心律不齐/i], '建议结合年龄、症状和医生意见判断是否需要随访', 'slight'),
  rule('ST_CHANGE', '心电图ST段改变', [/ST段改变/i, /ST改变/i], '建议结合症状和心电图随访进一步评估', 'abnormal'),
  rule('T_WAVE_CHANGE', '心电图T波改变', [/T波改变/i, /T波低平/i, /T波倒置/i], '建议结合症状和心电图随访进一步评估', 'slight'),
  rule('ST_T_CHANGE', '心电图ST-T改变', [/ST-T改变/i, /STT改变/i], '建议结合症状和心电图随访进一步评估', 'abnormal'),
  rule('ATRIAL_PREMATURE', '房性早搏', [/房性早搏/i], '建议结合症状和动态心电图进一步评估', 'abnormal'),
  rule('VENTRICULAR_PREMATURE', '室性早搏', [/室性早搏/i], '建议结合症状和动态心电图进一步评估', 'abnormal'),
  rule('RBBB_INCOMPLETE', '不完全右束支传导阻滞', [/不完全右束支传导阻滞/i], '建议结合心电图随访和心脏专科意见评估', 'slight'),
  rule('AV_BLOCK_FIRST', '一度房室传导阻滞', [/一度房室传导阻滞/i], '建议结合心电图随访和症状综合判断', 'slight'),
  rule('LVH_VOLTAGE', '左室高电压', [/左室高电压/i, /左心室高电压/i], '建议结合血压和超声心动图进一步评估', 'abnormal'),
  rule('MITRAL_REGURGITATION', '二尖瓣反流', [/二尖瓣反流/i], '建议结合超声心动图和心脏专科意见评估', 'slight'),
  rule('TRICUSPID_REGURGITATION', '三尖瓣反流', [/三尖瓣反流/i], '建议结合超声心动图和心脏专科意见评估', 'slight'),
  rule('AORTIC_REGURGITATION', '主动脉瓣反流', [/主动脉瓣反流/i], '建议结合超声心动图和心内科意见定期复查', 'slight'),
  rule('LV_DIASTOLIC_DYSFUNCTION', '左心室舒张功能减低', [/左心室舒张功能减低/i, /左室舒张功能减低/i, /舒张功能减低/i], '建议结合血压、心脏彩超和心内科意见综合评估', 'abnormal'),
  rule('VASCULAR_ELASTICITY_REDUCED', '血管弹性减弱', [/血管弹性(?:轻度|中度|重度)?减弱/i], '建议结合血压、血脂和动脉硬化风险进行系统管理', 'abnormal'),

  rule('CHRONIC_GASTRITIS', '慢性胃炎', [/慢性(?:浅表性|非萎缩性|萎缩性)?胃炎/i], '建议规律饮食并结合消化科意见评估是否需要复查胃镜', 'abnormal'),
  rule('SUPERFICIAL_GASTRITIS', '慢性浅表性胃炎', [/慢性浅表性胃炎/i], '建议规律饮食并结合消化科意见随访', 'slight'),
  rule('NON_ATROPHIC_GASTRITIS', '慢性非萎缩性胃炎', [/慢性非萎缩性胃炎/i], '建议规律饮食并结合消化科意见随访', 'slight'),
  rule('ATROPHIC_GASTRITIS', '萎缩性胃炎', [/萎缩性胃炎/i], '建议结合胃镜病理和消化科专科意见定期复查', 'abnormal'),
  rule('GASTRIC_POLYP', '胃息肉', [/胃息肉/i], '建议结合胃镜病理和消化科意见进一步评估', 'abnormal'),
  rule('REFLUX_ESOPHAGITIS', '反流性食管炎', [/反流性食管炎/i], '建议避免夜宵和刺激饮食，必要时消化科就诊', 'abnormal'),
  rule('DUODENITIS', '十二指肠球炎', [/十二指肠球炎/i, /十二指肠炎/i], '建议结合症状和消化科意见规范处理', 'slight'),
  rule('HP_POSITIVE', '幽门螺杆菌阳性', [/幽门螺杆菌.*阳性/i, /\bHP\b.*阳性/i, /H\.?\s*pylori.*阳性/i], '建议结合消化科意见评估是否需要根除治疗', 'abnormal'),
  rule('COLON_POLYP', '结肠息肉', [/结肠息肉/i, /肠息肉/i], '建议结合肠镜病理和消化科意见定期复查', 'abnormal'),
  rule('HEMORRHOIDS', '痔', [/痔疮/i, /内痔/i, /外痔/i, /混合痔/i], '建议结合症状、排便习惯和肛肠科意见评估', 'slight'),

  rule('REFRACTIVE_ERROR', '屈光不正', [/屈光不正/i], '建议结合验光结果和眼科意见评估视力矫正方案', 'slight', [/如既往[有无]屈光不正/i, /既往[有无]屈光不正/i]),
  rule('MYOPIA', '近视', [/近视/i], '建议结合视力和验光结果规范配镜或随访', 'slight'),
  rule('HYPEROPIA', '远视', [/远视/i], '建议结合视力和验光结果规范随访', 'slight'),
  rule('ASTIGMATISM', '散光', [/散光/i], '建议结合验光结果和视疲劳情况评估矫正方案', 'slight'),
  rule('VISION_DECLINE', '视力下降', [/视力下降/i, /裸眼视力下降/i, /视力欠佳/i], '建议结合眼科检查明确原因并及时干预', 'slight'),
  rule('DRY_EYE', '干眼', [/干眼/i, /干眼症/i], '建议结合用眼习惯调整和眼科意见处理', 'slight'),
  rule('CATARACT', '白内障', [/白内障/i], '建议结合眼科专科意见评估成熟度和处理方案', 'abnormal'),
  rule('FUNDUS_ARTERIOSCLEROSIS', '眼底动脉硬化', [/眼底动脉硬化/i], '建议结合血压、血脂和眼底复查综合管理', 'abnormal'),
  rule('PTERYGIUM', '翼状胬肉', [/翼状胬肉/i], '建议结合眼科意见评估是否影响视力或需处理', 'slight'),
  rule('VITREOUS_OPACITY', '玻璃体混浊', [/玻璃体混浊/i], '建议结合眼科检查明确是否与年龄或炎症相关', 'slight'),

  rule('DEVIATED_SEPTUM', '鼻中隔偏曲', [/鼻中隔偏曲/i], '建议结合鼻塞等症状和耳鼻喉科意见评估', 'slight'),
  rule('SINUSITIS', '鼻窦炎', [/鼻窦炎/i], '建议结合鼻部症状和耳鼻喉科意见规范处理', 'abnormal'),
  rule('CHRONIC_PHARYNGITIS', '慢性咽炎', [/慢性咽炎/i], '建议减少烟酒刺激并结合耳鼻喉科意见处理', 'slight'),
  rule('TONSIL_HYPERTROPHY', '扁桃体肥大', [/扁桃体肥大/i], '建议结合反复感染史和耳鼻喉科意见评估', 'slight'),
  rule('THYROID_CARTILAGE_NODULE', '声带小结', [/声带小结/i], '建议减少过度用嗓并结合耳鼻喉科意见随访', 'slight'),

  rule('DENTAL_CALCULUS', '牙结石', [/牙结石/i], '建议加强口腔清洁并定期洁牙', 'slight'),
  rule('DENTAL_CARIES', '龋齿', [/龋齿/i], '建议尽快口腔科就诊处理，避免进一步损伤', 'slight', [/龋齿无/i]),
  rule('PERIODONTITIS', '牙周炎', [/牙周炎/i], '建议加强口腔卫生并结合口腔科意见规范治疗', 'abnormal'),
  rule('GINGIVITIS', '牙龈炎', [/牙龈炎/i], '建议改善口腔清洁习惯并定期口腔复查', 'slight'),

  rule('OSTEOPENIA', '骨量减少', [/骨量减少/i], '建议结合骨密度、补钙维生素D和运动情况管理', 'slight'),
  rule('OSTEOPOROSIS', '骨质疏松', [/骨质疏松/i], '建议结合骨密度和骨代谢评估进行系统管理', 'abnormal'),
  rule('OSTEOPHYTE', '骨质增生', [/骨质增生/i], '建议结合疼痛症状和康复骨科意见评估', 'slight'),
  rule('CERVICAL_STRAIGHT', '颈椎曲度变直', [/颈椎曲度变直/i], '建议注意颈肩姿势并适当进行康复训练', 'slight'),
  rule('CERVICAL_DEGENERATION', '颈椎退行性变', [/颈椎退行性变/i], '建议结合颈肩症状和康复骨科意见评估', 'abnormal'),
  rule('LUMBAR_DEGENERATION', '腰椎退行性变', [/腰椎退行性变/i], '建议结合腰背痛症状和康复骨科意见评估', 'abnormal'),
  rule('LUMBAR_DISC', '腰椎间盘突出', [/腰椎间盘突出/i], '建议结合腰腿痛和康复骨科意见进一步评估', 'abnormal'),
  rule('BONE_SPUR', '骨赘形成', [/骨赘/i], '建议结合疼痛和活动受限情况综合评估', 'slight'),
  rule('SCOLIOSIS', '脊柱侧弯', [/脊柱侧弯/i], '建议结合影像程度和骨科意见进一步评估', 'abnormal'),
  rule('KNEE_DEGENERATION', '膝关节退行性变', [/膝关节退行性变/i], '建议结合体重管理和康复骨科意见综合处理', 'abnormal'),
  rule('LACUNAR_INFARCTION', '腔隙性脑梗塞', [/腔隙性脑梗塞/i, /腔隙性脑梗死/i], '建议结合神经内科意见和脑血管危险因素管理进一步评估', 'abnormal'),
  rule('CEREBRAL_ISCHEMIC_LESION', '脑内缺血灶', [/脑内缺血灶/i, /缺血灶/i], '建议结合脑血管危险因素和神经内科意见综合评估', 'abnormal'),
  rule('BRAIN_ATROPHY', '脑萎缩', [/脑萎缩/i], '建议结合年龄、认知情况和神经内科意见综合判断', 'slight'),
];

export const SPECIAL_FINDING_HEALTH_KEYWORDS: string[] = [
  '结节',
  '囊肿',
  '息肉',
  '增生',
  '肌瘤',
  '回声不均',
  'TCT',
  'HPV',
  'T波改变',
  'ST段改变',
  '屈光不正',
  '超重',
  '肥胖',
  '斑块',
  '结石',
  '积液',
  '钙化',
  '胃炎',
  '食管炎',
  '幽门螺杆菌',
  '白内障',
  '咽炎',
  '牙周炎',
  '骨质疏松',
  '退行性变',
  '脂肪肝',
  '外阴白斑',
  '主动脉瓣反流',
  '舒张功能减低',
  '血管弹性减弱',
  '脑梗塞',
  '脑萎缩',
  '视力欠佳',
];
